# Generated by Django 4.0.4 on 2022-05-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('F', 'First Player to move'), ('S', 'Second Player to move'), ('W', 'First Player Won'), ('L', 'Second Player Won'), ('D', 'Draw')], default='F', max_length=1),
        ),
    ]
