# Generated by Django 4.0.4 on 2022-05-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_alter_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='by_first_user',
            field=models.BooleanField(editable=False),
        ),
    ]
